# Generated by Django 5.1.1 on 2024-10-20 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lista', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lista',
            old_name='listas',
            new_name='user',
        ),
    ]
