# Generated by Django 5.1.1 on 2024-10-20 01:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_seguidores_user_seguindo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='seguidores',
            field=models.ManyToManyField(blank=True, related_name='lista_seguindo', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='seguindo',
            field=models.ManyToManyField(blank=True, related_name='lista_seguidores', to=settings.AUTH_USER_MODEL),
        ),
    ]
