# Generated by Django 5.1.1 on 2024-10-20 00:58

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Midia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('publish_date', models.DateField()),
                ('description', models.TextField()),
                ('studio', models.CharField(max_length=100)),
                ('banner', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Ação', 'Acao'), ('Terror', 'Terror'), ('Ficção Científica', 'Ficcao Cientifica'), ('Aventura', 'Aventura'), ('Drama', 'Drama'), ('Comédia', 'Comedia'), ('Romance', 'Romance'), ('Suspense', 'Suspense'), ('Musical', 'Musical'), ('RPG', 'Rpg'), ('Faroeste', 'Faroeste'), ('Policial', 'Policial'), ('Fantasia', 'Fantasia'), ('Documentário', 'Documentario'), ('Roguelike', 'Roguelike'), ('MOBA', 'Moba'), ('TPS', 'Tps'), ('Apocalipse', 'Apocalipse'), ('Arcade', 'Arcade'), ('Retro', 'Retro'), ('Online', 'Online'), ('Offline', 'Offline')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Platforms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('PC', 'Pc'), ('Playstation', 'Playstation'), ('Xbox', 'Xbox'), ('Nintendo', 'Nintendo'), ('Mobile', 'Mobile'), ('VR', 'Vr'), ('Netflix', 'Netflix'), ('Amazon Prime', 'Amazon Prime'), ('Disney Plus', 'Disney Plus'), ('HBO Max', 'Hbo Max'), ('Apple TV', 'Apple Tv'), ('Youtube', 'Youtube'), ('Twitch', 'Twitch'), ('Steam', 'Steam'), ('Origin', 'Origin'), ('Epic Games', 'Epic Games'), ('GOG', 'Gog'), ('Uplay', 'Uplay'), ('Battle.net', 'Battle Net'), ('Xbox Game Pass', 'Xbox Game Pass'), ('Playstation Now', 'Playstation Now'), ('Nintendo Online', 'Nintendo Online'), ('Google Play', 'Google Play'), ('App Store', 'App Store')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('midia_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='midia.midia')),
                ('publisher', models.CharField(max_length=100)),
                ('release_date', models.DateField()),
                ('avarage_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('avarage_playtime', models.TimeField()),
            ],
            bases=('midia.midia',),
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('midia_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='midia.midia')),
                ('duration', models.TimeField()),
                ('director', models.CharField(max_length=100)),
                ('cast', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, size=None)),
            ],
            bases=('midia.midia',),
        ),
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('midia_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='midia.midia')),
                ('seasons', models.IntegerField()),
                ('episodes', models.IntegerField()),
            ],
            bases=('midia.midia',),
        ),
        migrations.AddField(
            model_name='midia',
            name='genres',
            field=models.ManyToManyField(related_name='genres', to='midia.genres'),
        ),
        migrations.AddField(
            model_name='midia',
            name='platforms',
            field=models.ManyToManyField(related_name='platforms', to='midia.platforms'),
        ),
    ]
