# Generated by Django 5.1.1 on 2024-10-20 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('midia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='midia',
            name='genres',
            field=models.ManyToManyField(related_name='+', to='midia.genres'),
        ),
        migrations.AlterField(
            model_name='midia',
            name='platforms',
            field=models.ManyToManyField(related_name='+', to='midia.platforms'),
        ),
    ]
