# Generated by Django 5.1.1 on 2024-10-20 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('midia', '0003_alter_midia_genres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='midia',
            name='genres',
            field=models.ManyToManyField(related_name='+', to='midia.genres'),
        ),
    ]
