# Generated by Django 5.1.1 on 2024-11-20 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('midia', '0005_alter_midia_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='midia',
            name='banner',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
