# Generated by Django 5.1.1 on 2024-11-20 18:03

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('midia', '0006_alter_midia_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='cast',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, null=True, size=None),
        ),
    ]
