# Generated by Django 5.1.1 on 2024-11-20 18:18

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('midia', '0007_alter_movie_cast'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='midia',
            name='genres',
        ),
        migrations.DeleteModel(
            name='Genres',
        ),
        migrations.AddField(
            model_name='midia',
            name='genres',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, null=True, size=None),
        ),
    ]
