# Generated by Django 5.1.1 on 2024-11-20 19:19

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('midia', '0009_serie_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='midia',
            name='platforms',
        ),
        migrations.DeleteModel(
            name='Platforms',
        ),
        migrations.AddField(
            model_name='midia',
            name='platforms',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, null=True, size=None),
        ),
    ]
