# Generated by Django 5.1.1 on 2024-11-20 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('midia', '0010_remove_midia_platforms_delete_platforms_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='avarage_price',
        ),
        migrations.RemoveField(
            model_name='game',
            name='release_date',
        ),
    ]
