# Generated by Django 5.1.1 on 2024-11-23 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('midia', '0012_alter_game_avarage_playtime_alter_movie_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='midia',
            name='media_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
