# Generated by Django 5.1.1 on 2024-11-25 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('midia', '0006_alter_game_avarage_playtime'),
        ('midia', '0013_midia_media_type'),
    ]

    operations = [
    ]
