# Generated by Django 5.1.1 on 2024-11-25 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('midia', '0014_merge_20241125_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='avarage_playtime',
            field=models.DurationField(),
        ),
    ]
