# Generated by Django 5.1.1 on 2024-11-26 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('midia', '0015_alter_game_avarage_playtime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='midia',
            name='media_type',
        ),
        migrations.AddField(
            model_name='game',
            name='media_type',
            field=models.CharField(blank=True, default='game', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='media_type',
            field=models.CharField(blank=True, default='movie', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='serie',
            name='media_type',
            field=models.CharField(blank=True, default='serie', max_length=50, null=True),
        ),
    ]
