# Generated by Django 5.1.1 on 2024-11-26 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('midia', '0016_remove_midia_media_type_game_media_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='media_type',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='media_type',
        ),
        migrations.RemoveField(
            model_name='serie',
            name='media_type',
        ),
        migrations.AddField(
            model_name='midia',
            name='media_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
