# Generated by Django 5.1.1 on 2024-11-26 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0003_comment_created_at_review_created_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
